title = "LINQ to Fail"
baseURL = "https://www.aaron-powell.com"
tags = ["blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-6399564-1"
disqusShortname = "aaronpowell"
enableGitInfo = "true"
enableEmoji = "true"

[Params]
    tagline = "Aaron Powell - LINQ to Fail"
    author = "Aaron Powell"
    description = "Microsoft Cloud Developer Advocate"
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo.png"
    twitter = "slace"
    linkedin = "aaron-powell-66038631"
    github = "aaronpowell"
    email = "website-contact@aaron-powell.com"
    googleTagManager = ""
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

    # Code highlighting with highlight.js
    highlightJS = true
    highlightJSStyle = "/highlightjs/styles/github.css" # For custom highlight.js styles, add your /path/to/styles/default.css
    highlightJSScript = "/highlightjs/highlight.pack.js" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Speaking"
    url  = "/#speaking"
    weight = 3