title = "LINQ to Fail"
baseURL = "https://www.aaron-powell.com"
languageCode = "en-US"
config = "config.toml"
theme = "aaronpowell"
# theme = "timer-hugo"
canonifyURLS = true
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Blog"
        url     = "posts"
        weight  = 3
    [[menu.nav]]
        name    = "Talks"
        url     = "talks"
        weight  = 4
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 5
    [[menu.nav]]
        name    = "Search"
        url     = "search"
        weight  = 6

[params]
    home = "Home"
    tagline = "Aaron Powell - LINQ to Fail"
    author = "Aaron Powell"
    description = "Microsoft Cloud Developer Advocate"
    logo = "/images/logo-small.png"
    favicon = "favicon.ico"
    googleAnalytics = "UA-6399564-1"
    disqusShortname = "aaronpowell"
    opengraphImage = "/images/logo.png"
    email = "website-contact@aaron-powell.com"

    [params.banner]
        enable  = true
        bgImage = "images/hero.jpg"
        heading = "Hi, my name is Aaron and I'm a"
        description = "With over 15 years of software development experience and 10 years of public speaking. I'm active across a number of open source communities and this site shared my experiences."
        [[params.banner.flipText]]
            title   = "Developer"
        [[params.banner.flipText]]
            title   = "Speaker"
        [[params.banner.flipText]]
            title   = "Blogger"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "About Me"
        content = "Hello 👋, I'm a Cloud Developer Advocate for Microsoft based in Sydney. My area of specialty is front-end web development, focusing on architecture around SPA and other UI-heavy web applications."
        image   = "images/logo.png"

    [params.speaking]
        enable  = true
        title   = "Speaking"
        content = "I have a number of talks and workshops that I can give, or I can create something specific for your event. Check out the link below for my talk history and full bio."
        noTalks = "No upcoming talks. 😢"
        talks   = [
            { date = 2020-02-13, name = "MOD10 - Migrating Web Appliations to Azure", link = "https://www.microsoft.com/en-au/ignite-the-tour/sydney", event = "Microsoft Ignite The Tour | Sydney" },
            { date = 2020-02-13, name = "MOD30 - Enhancing Web Applications with Cloud Intelligence", link = "https://www.microsoft.com/en-au/ignite-the-tour/sydney", event = "Microsoft Ignite The Tour | Sydney" },
            { date = 2020-02-20, name = "MOD10 - Migrating Web Appliations to Azure", link = "https://www.microsoft.com/en-sg/ignite-the-tour/singapore", event = "Microsoft Ignite The Tour | Singapore" },
            { date = 2020-02-20, name = "MOD30 - Enhancing Web Applications with Cloud Intelligence", link = "https://www.microsoft.com/en-sg/ignite-the-tour/singapore", event = "Microsoft Ignite The Tour | Singapore" },
            { date = 2020-03-25, name = "MOD10 - Migrating Web Appliations to Azure", link = "https://www.microsoft.com/en-hk/ignite-the-tour/hong-kong", event = "Microsoft Ignite The Tour | Hong Kong" },
            { date = 2020-03-25, name = "MOD30 - Enhancing Web Applications with Cloud Intelligence", link = "https://www.microsoft.com/en-hk/ignite-the-tour/hong-kong", event = "Microsoft Ignite The Tour | Hong Kong" },
            { date = 2019-08-29, name = "Stateful Serverless through Durable Functions", link  = "https://www.serverlessdays.me/", event = "Serverles Days Melbourne" },
            { date = 2019-10-14, name = "React Workshop", link = "https://ndcsydney.com.au", event = "NDC Sydney" },
            { date = 2019-10-16, name = "Being cheap with the cloud", link = "https://ndcsydney.com.au", event = "NDC Sydney" },
            { date = 2019-07-31, name = "Stateful Serverless through Durable Functions", link = "https://www.meetup.com/Perth-Serverless/events/262089134/", event = "Perth Serverless Meetup" },
            { date = 2019-08-10, name = "A career shaped by DDD Melbourne", link = "https://dddmelbourne.com/agenda/2019", event = "DDD Melbourne" },
            { date = 2019-06-20, name = "WebAssembly, your browser's sandbox", link = "https://www.webdirections.org/code19/speakers/aaron-powell.php", event = "Web Directions Code" },
            { date = 2019-05-09, name = "Stateful Serverless through Durable Functions", link = "https://www.aaron-powell.com/talks/stateful-serverless-through-durable-functions", event = "Microsoft Melbourne" },
            { date = 2019-05-09, name = "Docker, FROM scratch", link = "https://www.aaron-powell.com/talks/docker-from-scratch", event = "Monash University" },
            { date = 2019-04-11, name = "Go...ing with WebAssembly", link = "https://www.meetup.com/frontendtech/events/259517441/", event = "SydPWA" },
            { date = 2019-03-21, name = "Go...ing with WebAssembly", link = "https://www.meetup.com/golang-syd/events/259576939/", event = "golang-syd" },
            { date = 2019-02-13, name = "Docker, FROM scratch", link = "https://www.microsoft.com/en-au/ignite-the-tour/sydney", event = "Microsoft Ignite The Tour | Sydney" },
            { date = 2019-09-17, name = "React Workshop", link = "https://ndcsydney.com.au", event = "NDC Sydney" },
            { date = 2019-09-19, name = "The Beauty of Stupid Ideas", link = "https://ndcsydney.com.au", event = "NDC Sydney" }
        ]
    [params.speaking.bio]
        short   = "I like long walks on the beach talking about JavaScript"
        long    = "Aaron is a Developer Advocate at Microsoft. Having spent 15 years doing web development he's seen it all, from browser wars, the rise of AJAX and the fall of 20 JavaScript frameworks (and that was just yesterday!). Always tinkering with something new he explores crazy ideas like writing your own implementation of numbers in .NET, creating IoC in JavaScript or implementing tic-tac-toe using git commits."
        avatar  = "/images/logo.png"
        twitter = "slace"

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-logo-twitter"
            url = "https://twitter.com/slace"
            title = "Twitter"

        [[params.footer.socialIcon]]
            icon = "ion-logo-github"
            url = "https://github.com/aaronpowell"
            title = "GitHub"

        [[params.footer.socialIcon]]
            icon = "ion-logo-linkedin"
            url = "https://www.linkedin.com/in/aaron-powell-66038631/"
            title = "LinkedIn"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true