name: Build and Deploy Website

on:
  push:
    branches:
      - search

jobs:
  build_hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: "0.54.0"

      - name: Build
        run: hugo --minify --source ./src --destination ../.output

      - name: Publish website output
        uses: actions/upload-artifact@v1
        with:
          name: website
          path: ./.output

      - name: Publish blog json
        uses: actions/upload-artifact@v1
        with:
          name: json
          path: ./.output/index.json

  build_search_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.100-preview3-014645"

      - name: Build search app
        run: dotnet build --configuration Release
        working-directory: ./Search

      - name: Publish search UI
        run: dotnet publish --no-build --configuration Release --output ../../.output
        working-directory: ./Search/Search.Site.UI

      - name: Package search UI
        uses: actions/upload-artifact@v1
        with:
          name: search
          path: ./.output/Search.Site.UI/dist/_framework

  build_search_index:
    runs-on: ubuntu-latest
    needs: build_hugo
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.100-preview3-014645"

      - name: Download index source
        uses: actions/download-artifact@v1
        with:
          name: json
          path: ./.output

      - name: Build search index
        run: dotnet run
        working-directory: ./Search/Search.IndexBuilder

      - name: Publish search index
        uses: actions/upload-artifact@v1
        with:
          name: search-index
          path: ./Search/Search.IndexBuilder/index.zip

  deploy_website:
    runs-on: ubuntu-latest
    needs: [build_search_ui, build_search_index]
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download website
        uses: actions/download-artifact@v1
        with:
          name: website
          path: ./.output

      - name: Download search UI
        uses: actions/download-artifact@v1
        with:
          name: search
          path: ./.output-search

      - name: Download search indez
        uses: actions/download-artifact@v1
        with:
          name: search-index
          path: ./.output

      - name: Move Search UI into website
        run: cp -r ./.output-search/search ./.output

      - name: Deploy to Azure Storage
        run: az storage blob upload-batch --source ./.output --destination \$web/${GITHUB_SHA} --account-name aaronpowellstaticwebsite