name: Build and Deploy Website

on:
  push:
    branches:
      - search

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: "0.54.0"

      - name: Build
        run: hugo --minify --source ./src --output ./output
